config/routes.rb
Szablafour::Application.routes.draw do
  resources :seasons

  resources :tournaments

  resources :resolutions

  resources :rounds

  resources :teams

  resources :people

  resources :colleges

end

app/models/college.rb
class College < ActiveRecord::Base
    has_many :persons
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @colleges }
    end
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
    @college = College.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @college }
    end
  end

  # GET /colleges/new
  # GET /colleges/new.json
  def new
    @college = College.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @college }
    end
  end

  # GET /colleges/1/edit
  def edit
    @college = College.find(params[:id])
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(params[:college])

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render json: @college, status: :created, location: @college }
      else
        format.html { render action: "new" }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /colleges/1
  # PUT /colleges/1.json
  def update
    @college = College.find(params[:id])

    respond_to do |format|
      if @college.update_attributes(params[:college])
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college = College.find(params[:id])
    @college.destroy

    respond_to do |format|
      format.html { redirect_to colleges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/_form.html.erb
<%= form_for(@college) do |f| %>
  <% if @college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% @college.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :locaiton %><br />
    <%= f.text_field :locaiton %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<h1>Editing college</h1>

<%= render 'form' %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

app/views/colleges/index.html.erb
<h1>Listing colleges</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Locaiton</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @colleges.each do |college| %>
  <tr>
    <td><%= college.name %></td>
    <td><%= college.locaiton %></td>
    <td><%= link_to 'Show', college %></td>
    <td><%= link_to 'Edit', edit_college_path(college) %></td>
    <td><%= link_to 'Destroy', college, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New College', new_college_path %>

app/views/colleges/new.html.erb
<h1>New college</h1>

<%= render 'form' %>

<%= link_to 'Back', colleges_path %>

app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @college.name %>
</p>

<p>
  <b>Locaiton:</b>
  <%= @college.locaiton %>
</p>


<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>